package com.michael.contract.resources.validations.enums;

public enum Tag {
  LANGUAGE,
  FRAMEWORK,
  RUNTIME_VERSION,
  IS_CONTAINERIZED,
  DATABASE,
  CACHE,
  API_VERSION,
  MESSAGE_BROKER,
  UI_FRAMEWORK,
  BUILD_TOOL,
  OS,
  CLOUD_PROVIDER,
  WEB_SERVER,
  VERSION_CONTROL,
  DEPENDENCIES,
  ENVIRONMENT,
  MONITORING_TOOL,
  LOGGING_TOOL,
  SCALABILITY,
  GEO_REGION,
  SUPPORT_CONTACT,
  LICENSE,
  API_DOCUMENTATION,
  SUPPORT_URL
}
