services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: >
      sh -c "
        redis-server --notify-keyspace-events 'Ex' &&
        tail -f /dev/null
      "
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
  service-registry:
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    environment:
      - ETCD_URLS
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9095"
    networks:
      - app-network
    healthcheck:
      test: "curl --fail --silent http://service-registry:9095/service-registry/api/v2/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
networks:
  app-network:
    driver: bridge